export default [
  {
    id: 1,
    title: 'Danmarks Indsamling 2022: hjælp coronakrisens børn',
    date: '29.01.2022',
    description:
      '<p>Coronapandemien har forandret vores verden. I Danmark må vi leve med afstand og nye restriktioner, og epidemien gør hverdagen svær for mange. Men i verdens fattigste lande er situationen langt mere katastrofal, og hvor nøden før var stor, er den nu ekstrem.</p><p>Konsekvenserne rammer alle, men det er børnene, der risikerer at blive de største ofre. Millioner er lige nu sat udenfor skolesystemet, og deres håb om en bedre fremtid forsvinder langsomt, mens fattigdommen vokser og sulten tager over. Risikoen for en barndom med børnearbejde eller&nbsp;som barnebrud er overhængende.</p><p>Med udviklingsprojekter i 12 lande, giver Danmarks Indsamling børnene nyt håb og nye muligheder på trods af corona. Vi hjælper dér, hvor nøden er størst. Vi sikrer, at børnene får adgang til rent drikkevand; at de får uddannelse og beskyttelse; at der er en læge, der kan hjælpe, og en voksen, der kan give dem den omsorg, de har brug for.</p><p>Vi gør det, fordi vi er et lille land med et stort hjerte. Vi gør det nu, fordi coronakrisens børn har akut brug for vores hjælp. Og vi gør det sammen, fordi ingen kan gøre det alene.</p><p>Se med, når hele Danmark samler ind i den gode sags tjeneste lørdag d. 29. januar på DR1.</p>',
    organizer: [
      'Folkekirkens nødhjælp',
      'Unicef',
      'SOS Børnebyerne',
      'Røde kors',
      'Red barnet',
      'Mellemfolkeligt samvirke',
      'Læger uden grænser',
      'Oxfarm IBIS',
      'Dansk flygtningehjælp',
    ],
    eventLink: 'https://danmarksindsamling.dk/',
    imageLink: './assets/images/DanmarksIndsamling2022.PNG',
    tags: [''],
  },
  {
    id: 2,
    title: 'Danmark samler ind til klimaløsninger',
    date: '13.03.2022',
    description:
      '<h2><strong>Danmark samler ind til klimaløsninge</strong>r</h2><p>For hver dag, der går, ses&nbsp;klimakrisens konsekvenser&nbsp;tydeligere og tydeligere.&nbsp;</p><p>Derfor vil omkring 15.000 danskere <strong><strong>søndag d. 13. marts 2022</strong> </strong>samle ind til dem, der er hårdest ramt. Oftest er det dem, som har det mindste klimaaftryk, der dybt uretfærdigt rammes hårdest. </p><p>Du kan også være med til at samle ind og gøre en forskel. Hver gang du samler en 20’er eller en 50’er ind, er du med til at gøre en konkret forskel for en hel familie i en af verdens fattigste lande. </p><p>Det er ganske enkelt – alle beløb gør en forskel, når vi sammen hjælper <strong>verdens fattigste</strong>&nbsp;med at takle klimaforandringerne. </p><h2><strong>Hvor og hvornår er sogneindsamlingen 2022</strong>?</h2><ul><li>Sogneindsamlingen er <strong>søndag d. 13. marts 2022</strong></li></ul><ul><li>Sogneindsamlingen foregår <strong>i dit lokale område</strong></li></ul><ul><li>Du kan være <strong>indsamler, indsamlingsleder eller oprette din egen digitale indsamling</strong></li></ul>',
    organizer: 'Folkekirkens nødhjælp',
    eventLink: 'https://www.noedhjaelp.dk/indsamling',
    imageLink: './assets/images/Sogneindsamling2022.PNG',
    tags: ['Folkekirkens nødhjælp'],
  },
  {
    id: 3,
    title: 'Indsamling 3',
    description: 'Beskrivelse af ndsamling 3',
    organizer: 'Red barnet',
    done: true,
  },
  {
    id: 4,
    title: 'Indsamling 4',
    description: 'Beskrivelse af ndsamling 4',
    organizer: 'Unicef',
    done: true,
  },
  {
    id: 5,
    title: 'Indsamling 5',
    description: 'Beskrivelse af indsamling 5',
    organizer: 'Kræftens bekæmpelse',
    done: true,
  },
  {
    id: 6,
    title: 'Indsamling 6',
    description: 'Beskrivelse af indsamling 6',
    organizer: 'Kræftens bekæmpelse',
    done: true,
  },
];
